version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /500.html
    destination: /var/www/html/
  - source: /503.html
    destination: /var/www/html/
  - source: /broken.php
    destination: /var/www/html/
  - source: /unavailable.php
    destination: /var/www/html/
  - source: /.htaccess
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
